//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDriveWPF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/MyDriveService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyDriveWPF.ServiceReference1.Roles RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyDriveWPF.ServiceReference1.Roles Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Roles", Namespace="http://schemas.datacontract.org/2004/07/MyDriveService")]
    public enum Roles : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        trial = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        simple = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        maximum = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerUserResponse", Namespace="http://schemas.datacontract.org/2004/07/MyDriveService")]
    [System.SerializableAttribute()]
    public partial class AnswerUserResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyDriveWPF.ServiceReference1.AnswerCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyDriveWPF.ServiceReference1.User _UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyDriveWPF.ServiceReference1.AnswerCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyDriveWPF.ServiceReference1.User _User {
            get {
                return this._UserField;
            }
            set {
                if ((object.ReferenceEquals(this._UserField, value) != true)) {
                    this._UserField = value;
                    this.RaisePropertyChanged("_User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerCode", Namespace="http://schemas.datacontract.org/2004/07/MyDriveService")]
    public enum AnswerCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Complete = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerResponse", Namespace="http://schemas.datacontract.org/2004/07/MyDriveService")]
    [System.SerializableAttribute()]
    public partial class AnswerResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyDriveWPF.ServiceReference1.AnswerCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyDriveWPF.ServiceReference1.StorageFile[] FilesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyDriveWPF.ServiceReference1.AnswerCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyDriveWPF.ServiceReference1.StorageFile[] Files {
            get {
                return this.FilesField;
            }
            set {
                if ((object.ReferenceEquals(this.FilesField, value) != true)) {
                    this.FilesField = value;
                    this.RaisePropertyChanged("Files");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StorageFile", Namespace="http://schemas.datacontract.org/2004/07/MyDriveService")]
    [System.SerializableAttribute()]
    public partial class StorageFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAccessService")]
    public interface IAccessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/UserRegistration", ReplyAction="http://tempuri.org/IAccessService/UserRegistrationResponse")]
        MyDriveWPF.ServiceReference1.AnswerUserResponse UserRegistration(MyDriveWPF.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/UserRegistration", ReplyAction="http://tempuri.org/IAccessService/UserRegistrationResponse")]
        System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerUserResponse> UserRegistrationAsync(MyDriveWPF.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/UserAuth", ReplyAction="http://tempuri.org/IAccessService/UserAuthResponse")]
        MyDriveWPF.ServiceReference1.AnswerUserResponse UserAuth(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessService/UserAuth", ReplyAction="http://tempuri.org/IAccessService/UserAuthResponse")]
        System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerUserResponse> UserAuthAsync(string login, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccessServiceChannel : MyDriveWPF.ServiceReference1.IAccessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessServiceClient : System.ServiceModel.ClientBase<MyDriveWPF.ServiceReference1.IAccessService>, MyDriveWPF.ServiceReference1.IAccessService {
        
        public AccessServiceClient() {
        }
        
        public AccessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MyDriveWPF.ServiceReference1.AnswerUserResponse UserRegistration(MyDriveWPF.ServiceReference1.User user) {
            return base.Channel.UserRegistration(user);
        }
        
        public System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerUserResponse> UserRegistrationAsync(MyDriveWPF.ServiceReference1.User user) {
            return base.Channel.UserRegistrationAsync(user);
        }
        
        public MyDriveWPF.ServiceReference1.AnswerUserResponse UserAuth(string login, string password) {
            return base.Channel.UserAuth(login, password);
        }
        
        public System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerUserResponse> UserAuthAsync(string login, string password) {
            return base.Channel.UserAuthAsync(login, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStorrageService")]
    public interface IStorrageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/Create", ReplyAction="http://tempuri.org/IStorrageService/CreateResponse")]
        MyDriveWPF.ServiceReference1.AnswerResponse Create(byte[] file, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/Create", ReplyAction="http://tempuri.org/IStorrageService/CreateResponse")]
        System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> CreateAsync(byte[] file, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/CreateFolder", ReplyAction="http://tempuri.org/IStorrageService/CreateFolderResponse")]
        MyDriveWPF.ServiceReference1.AnswerResponse CreateFolder(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/CreateFolder", ReplyAction="http://tempuri.org/IStorrageService/CreateFolderResponse")]
        System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> CreateFolderAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/Delete", ReplyAction="http://tempuri.org/IStorrageService/DeleteResponse")]
        MyDriveWPF.ServiceReference1.AnswerResponse Delete(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/Delete", ReplyAction="http://tempuri.org/IStorrageService/DeleteResponse")]
        System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> DeleteAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/Update", ReplyAction="http://tempuri.org/IStorrageService/UpdateResponse")]
        MyDriveWPF.ServiceReference1.AnswerResponse Update(byte[] file, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/Update", ReplyAction="http://tempuri.org/IStorrageService/UpdateResponse")]
        System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> UpdateAsync(byte[] file, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/Read", ReplyAction="http://tempuri.org/IStorrageService/ReadResponse")]
        MyDriveWPF.ServiceReference1.AnswerResponse Read(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/Read", ReplyAction="http://tempuri.org/IStorrageService/ReadResponse")]
        System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> ReadAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/ReadAll", ReplyAction="http://tempuri.org/IStorrageService/ReadAllResponse")]
        MyDriveWPF.ServiceReference1.AnswerResponse ReadAll(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/ReadAll", ReplyAction="http://tempuri.org/IStorrageService/ReadAllResponse")]
        System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> ReadAllAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/GetFreeSpace", ReplyAction="http://tempuri.org/IStorrageService/GetFreeSpaceResponse")]
        int GetFreeSpace(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/GetFreeSpace", ReplyAction="http://tempuri.org/IStorrageService/GetFreeSpaceResponse")]
        System.Threading.Tasks.Task<int> GetFreeSpaceAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/GetAllSpace", ReplyAction="http://tempuri.org/IStorrageService/GetAllSpaceResponse")]
        int GetAllSpace(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/GetAllSpace", ReplyAction="http://tempuri.org/IStorrageService/GetAllSpaceResponse")]
        System.Threading.Tasks.Task<int> GetAllSpaceAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/SearchFiles", ReplyAction="http://tempuri.org/IStorrageService/SearchFilesResponse")]
        MyDriveWPF.ServiceReference1.AnswerResponse SearchFiles(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/SearchFiles", ReplyAction="http://tempuri.org/IStorrageService/SearchFilesResponse")]
        System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> SearchFilesAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/SearchDirectories", ReplyAction="http://tempuri.org/IStorrageService/SearchDirectoriesResponse")]
        MyDriveWPF.ServiceReference1.AnswerResponse SearchDirectories(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/SearchDirectories", ReplyAction="http://tempuri.org/IStorrageService/SearchDirectoriesResponse")]
        System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> SearchDirectoriesAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/OpenFolder", ReplyAction="http://tempuri.org/IStorrageService/OpenFolderResponse")]
        MyDriveWPF.ServiceReference1.AnswerResponse OpenFolder(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/OpenFolder", ReplyAction="http://tempuri.org/IStorrageService/OpenFolderResponse")]
        System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> OpenFolderAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/RenameFolder", ReplyAction="http://tempuri.org/IStorrageService/RenameFolderResponse")]
        MyDriveWPF.ServiceReference1.AnswerResponse RenameFolder(string oldPahr, string newPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorrageService/RenameFolder", ReplyAction="http://tempuri.org/IStorrageService/RenameFolderResponse")]
        System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> RenameFolderAsync(string oldPahr, string newPath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStorrageServiceChannel : MyDriveWPF.ServiceReference1.IStorrageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StorrageServiceClient : System.ServiceModel.ClientBase<MyDriveWPF.ServiceReference1.IStorrageService>, MyDriveWPF.ServiceReference1.IStorrageService {
        
        public StorrageServiceClient() {
        }
        
        public StorrageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StorrageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorrageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorrageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MyDriveWPF.ServiceReference1.AnswerResponse Create(byte[] file, string path) {
            return base.Channel.Create(file, path);
        }
        
        public System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> CreateAsync(byte[] file, string path) {
            return base.Channel.CreateAsync(file, path);
        }
        
        public MyDriveWPF.ServiceReference1.AnswerResponse CreateFolder(string path) {
            return base.Channel.CreateFolder(path);
        }
        
        public System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> CreateFolderAsync(string path) {
            return base.Channel.CreateFolderAsync(path);
        }
        
        public MyDriveWPF.ServiceReference1.AnswerResponse Delete(string name) {
            return base.Channel.Delete(name);
        }
        
        public System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> DeleteAsync(string name) {
            return base.Channel.DeleteAsync(name);
        }
        
        public MyDriveWPF.ServiceReference1.AnswerResponse Update(byte[] file, string path) {
            return base.Channel.Update(file, path);
        }
        
        public System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> UpdateAsync(byte[] file, string path) {
            return base.Channel.UpdateAsync(file, path);
        }
        
        public MyDriveWPF.ServiceReference1.AnswerResponse Read(string path) {
            return base.Channel.Read(path);
        }
        
        public System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> ReadAsync(string path) {
            return base.Channel.ReadAsync(path);
        }
        
        public MyDriveWPF.ServiceReference1.AnswerResponse ReadAll(string path) {
            return base.Channel.ReadAll(path);
        }
        
        public System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> ReadAllAsync(string path) {
            return base.Channel.ReadAllAsync(path);
        }
        
        public int GetFreeSpace(int id) {
            return base.Channel.GetFreeSpace(id);
        }
        
        public System.Threading.Tasks.Task<int> GetFreeSpaceAsync(int id) {
            return base.Channel.GetFreeSpaceAsync(id);
        }
        
        public int GetAllSpace(int id) {
            return base.Channel.GetAllSpace(id);
        }
        
        public System.Threading.Tasks.Task<int> GetAllSpaceAsync(int id) {
            return base.Channel.GetAllSpaceAsync(id);
        }
        
        public MyDriveWPF.ServiceReference1.AnswerResponse SearchFiles(string path) {
            return base.Channel.SearchFiles(path);
        }
        
        public System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> SearchFilesAsync(string path) {
            return base.Channel.SearchFilesAsync(path);
        }
        
        public MyDriveWPF.ServiceReference1.AnswerResponse SearchDirectories(string path) {
            return base.Channel.SearchDirectories(path);
        }
        
        public System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> SearchDirectoriesAsync(string path) {
            return base.Channel.SearchDirectoriesAsync(path);
        }
        
        public MyDriveWPF.ServiceReference1.AnswerResponse OpenFolder(string path) {
            return base.Channel.OpenFolder(path);
        }
        
        public System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> OpenFolderAsync(string path) {
            return base.Channel.OpenFolderAsync(path);
        }
        
        public MyDriveWPF.ServiceReference1.AnswerResponse RenameFolder(string oldPahr, string newPath) {
            return base.Channel.RenameFolder(oldPahr, newPath);
        }
        
        public System.Threading.Tasks.Task<MyDriveWPF.ServiceReference1.AnswerResponse> RenameFolderAsync(string oldPahr, string newPath) {
            return base.Channel.RenameFolderAsync(oldPahr, newPath);
        }
    }
}
